import 'dart:ui';
import 'package:flutter/material.dart';

const Color graycol = Color(0xFF74777D);
const Color black = Color(0xFF060D17);
const Color green = Color(0xFF6BBC3B);
const scaffoldColor = Color(0xFFFAFAFA);
const whiteColor = Color(0xFFFFFFFF);
const textFiledColor = Color(0xFF9CA3AF);
const textFiledBorderColor = Color(0xFF8E8E8E);
const redColor = Color(0xFFEF4444);
const yellowColor = Color(0xFFFCE34C);
const textColor = Color(0xFF1F1F1F);
const borderColor = Color(0xFFE1E1E1);
const greyColor = Color(0xFF4B4B4B);
const iconColor = Color(0xFF293644);
const lightYellowColor = Color(0xFFFEF4B7);
const lightGreyColor = Color(0xFFF5F5F5);
const redButtonColor = Color(0xFFEC2D30);
const greenColor = Color(0xFF0C9D61);
const lgreen = Color(0xEEF7E2CC);
const litegreen = Color(0xFFc6fd9b);
const newC = Color(0xFFF0F0F0);
const litegray = Color(0xFFF7F7F7);
const liteDarkgrey=Color(0xFF696969);
